# SPDX-License-Identifier: GPL-3.0-or-later
# GENERATED by tools/generate_icons.py – do not edit manually.
# Edit the SVG files in pdf_signer/icons/ and re-run the generator.
"""SVG icon definitions and helper for PDF QES Signer toolbar."""

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QIcon, QPixmap, QPainter
from PyQt6.QtSvg import QSvgRenderer


# ---------------------------------------------------------------------------
# SVG sources  (viewBox="0 0 16 16", currentColor as colour placeholder)
# ---------------------------------------------------------------------------

ICON_BOTTOM = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <path fill="currentColor" d="M3 5 L13 5 L8 11 Z"/>\n  <path fill="currentColor" d="M3 9 L13 9 L8 15 Z"/>\n</svg>'

ICON_CHEVRON_DOWN = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <path fill="currentColor" d="M3 5 L8 11 L13 5 Z"/>\n</svg>'

ICON_CHEVRON_UP = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <path fill="currentColor" d="M3 11 L8 5 L13 11 Z"/>\n</svg>'

ICON_MULTI_PAGE = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <!-- oberes Blatt: linke, untere, rechte Kante (oben offen) -->\n  <path d="M3.5 3 L3.5 6.5 Q3.5 7 4 7 L12 7 Q12.5 7 12.5 6.5 L12.5 3"\n        fill="none" stroke="currentColor" stroke-width="1.2"\n        stroke-linecap="square" stroke-linejoin="round"/>\n  <line x1="7.5" y1="3" x2="10.5" y2="3" stroke="currentColor" stroke-width="0.9"/>\n  <line x1="5.5" y1="5" x2="10.5" y2="5" stroke="currentColor" stroke-width="0.9"/>\n\n  <!-- unteres Blatt: vollständiges Rect, unten offen -->\n  <path d="M3.5 13 L3.5 10 Q3.5 9.5 4 9.5 L12 9.5 Q12.5 9.5 12.5 10 L12.5 13"\n        fill="none" stroke="currentColor" stroke-width="1.2"\n        stroke-linecap="square" stroke-linejoin="round"/>\n  <line x1="5.5" y1="12" x2="10.5" y2="12" stroke="currentColor" stroke-width="0.9"/>\n</svg>'

ICON_PAGE_HEIGHT = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <rect x="5" y="4" width="6" height="8" rx="0.4" fill="none" stroke="currentColor" stroke-width="1.1"/>\n  <line x1="8" y1="1" x2="8" y2="4" stroke="currentColor" stroke-width="1.1"/>\n  <polyline points="6,2.5 8,1 10,2.5" fill="none" stroke="currentColor" stroke-width="1.1" stroke-linejoin="round"/>\n  <line x1="8" y1="12" x2="8" y2="15" stroke="currentColor" stroke-width="1.1"/>\n  <polyline points="6,13.5 8,15 10,13.5" fill="none" stroke="currentColor" stroke-width="1.1" stroke-linejoin="round"/>\n</svg>'

ICON_PAGE_WIDTH = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <rect x="5.3" y="3" width="5.4" height="10" rx="0.4" fill="none" stroke="currentColor" stroke-width="1.1"/>\n  <line x1="1" y1="8" x2="5.3" y2="8" stroke="currentColor" stroke-width="1.1"/>\n  <polyline points="2.5,6 1,8 2.5,10" fill="none" stroke="currentColor" stroke-width="1.1" stroke-linejoin="round"/>\n  <line x1="10.7" y1="8" x2="15" y2="8" stroke="currentColor" stroke-width="1.1"/>\n  <polyline points="13.5,6 15,8 13.5,10" fill="none" stroke="currentColor" stroke-width="1.1" stroke-linejoin="round"/>\n</svg>'

ICON_SINGLE_PAGE = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <rect x="4" y="2" width="8" height="10" rx="0.5" fill="none" stroke="currentColor" stroke-width="1.2"/>\n  <line x1="6" y1="5.5" x2="10" y2="5.5" stroke="currentColor" stroke-width="1"/>\n  <line x1="6" y1="7.5" x2="10" y2="7.5" stroke="currentColor" stroke-width="1"/>\n  <line x1="6" y1="9.5" x2="9" y2="9.5" stroke="currentColor" stroke-width="1"/>\n  <rect x="4" y="13" width="8" height="1.2" rx="0.3" fill="currentColor" opacity="0.25"/>\n</svg>'

ICON_TOP = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <path fill="currentColor" d="M3 7 L8 1 L13 7 Z"/>\n  <path fill="currentColor" d="M3 11 L8 5 L13 11 Z"/>\n</svg>'

ICON_ZOOM_IN = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <circle cx="7" cy="7" r="4.5" fill="none" stroke="currentColor" stroke-width="1.2"/>\n  <line x1="5" y1="7" x2="9" y2="7" stroke="currentColor" stroke-width="1.2"/>\n  <line x1="7" y1="5" x2="7" y2="9" stroke="currentColor" stroke-width="1.2"/>\n  <line x1="10.5" y1="10.5" x2="14" y2="14" stroke="currentColor" stroke-width="1.3"/>\n</svg>'

ICON_ZOOM_OUT = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">\n  <circle cx="7" cy="7" r="4.5" fill="none" stroke="currentColor" stroke-width="1.2"/>\n  <line x1="5" y1="7" x2="9" y2="7" stroke="currentColor" stroke-width="1.2"/>\n  <line x1="10.5" y1="10.5" x2="14" y2="14" stroke="currentColor" stroke-width="1.3"/>\n</svg>'


ICONS: dict[str, str] = {
    'bottom': ICON_BOTTOM,
    'chevron_down': ICON_CHEVRON_DOWN,
    'chevron_up': ICON_CHEVRON_UP,
    'multi_page': ICON_MULTI_PAGE,
    'page_height': ICON_PAGE_HEIGHT,
    'page_width': ICON_PAGE_WIDTH,
    'single_page': ICON_SINGLE_PAGE,
    'top': ICON_TOP,
    'zoom_in': ICON_ZOOM_IN,
    'zoom_out': ICON_ZOOM_OUT,
}


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def svg_to_icon(svg: str, size: int = 20, color: str = "#3a3a3a") -> QIcon:
    """Render an SVG string as a QIcon.

    ``currentColor`` in the SVG is replaced with *color* before rendering so
    the icon works correctly with QSvgRenderer (which has no CSS cascade).
    """
    svg_colored = svg.replace("currentColor", color)
    renderer = QSvgRenderer(svg_colored.encode())
    pixmap = QPixmap(size, size)
    pixmap.fill(Qt.GlobalColor.transparent)
    painter = QPainter(pixmap)
    renderer.render(painter)
    painter.end()
    return QIcon(pixmap)
