#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate pdf_signer/icons.py from SVG files in pdf_signer/icons/.

Usage (from project root):
    python tools/generate_icons.py
"""

from pathlib import Path

ICONS_DIR = Path(__file__).parent.parent / "pdf_signer" / "icons"
OUTPUT    = Path(__file__).parent.parent / "pdf_signer" / "icons.py"

HEADER = '''\
# SPDX-License-Identifier: GPL-3.0-or-later
# GENERATED by tools/generate_icons.py – do not edit manually.
# Edit the SVG files in pdf_signer/icons/ and re-run the generator.
"""SVG icon definitions and helper for PDF QES Signer toolbar."""

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QIcon, QPixmap, QPainter
from PyQt6.QtSvg import QSvgRenderer


# ---------------------------------------------------------------------------
# SVG sources  (viewBox="0 0 16 16", currentColor as colour placeholder)
# ---------------------------------------------------------------------------
'''

FOOTER = '''

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def svg_to_icon(svg: str, size: int = 20, color: str = "#3a3a3a") -> QIcon:
    """Render an SVG string as a QIcon.

    ``currentColor`` in the SVG is replaced with *color* before rendering so
    the icon works correctly with QSvgRenderer (which has no CSS cascade).
    """
    svg_colored = svg.replace("currentColor", color)
    renderer = QSvgRenderer(svg_colored.encode())
    pixmap = QPixmap(size, size)
    pixmap.fill(Qt.GlobalColor.transparent)
    painter = QPainter(pixmap)
    renderer.render(painter)
    painter.end()
    return QIcon(pixmap)
'''


def main() -> None:
    svg_files = sorted(ICONS_DIR.glob("*.svg"))
    if not svg_files:
        raise SystemExit(f"No SVG files found in {ICONS_DIR}")

    lines = [HEADER]
    names = []

    for svg_path in svg_files:
        const_name = "ICON_" + svg_path.stem.upper()
        names.append((svg_path.stem, const_name))
        svg_content = svg_path.read_text(encoding="utf-8").rstrip()
        lines.append(f"{const_name} = {repr(svg_content)}\n")

    lines.append("\nICONS: dict[str, str] = {")
    for stem, const_name in names:
        lines.append(f'    {repr(stem)}: {const_name},')
    lines.append("}")

    lines.append(FOOTER)

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {OUTPUT}  ({len(names)} icons)")


if __name__ == "__main__":
    main()
